databases:
  - name: storage/development.sqlite3
    databaseName: storage/development.sqlite3
    user: username
    plan: free

services:
  - type: web
    name: mysite
    runtime: ruby
    plan: free
    buildCommand: bundle install; bundle exec rake assets:precompile; bundle exec rake assets:clean;
    # preDeployCommand: "bundle exec rails db:migrate" # preDeployCommand only available on paid instance types
    startCommand: bundle exec puma -t 5:5 -p ${PORT:-3000} -e ${RACK_ENV:-development}
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mysite
          property: connectionString
      - key: 62303d7497a58f94362a1ee307f22df3
        sync: false
      - key: WEB_CONCURRENCY
        value: 2 # sensible default
